name: deploy pipeline
run-name: ${{ github.actor }} is deploying vsynth
on: [push]
jobs:
  configure-update:
    runs-on: self-hosted
    steps:
      - name: pull from repo
        env:
          PROJECT_PATH: ${{secrets.PROJECT_PATH}}
          PROJECTS_PATH: ${{secrets.PROJECTS_PATH}}
        run: |
          if [ ! -d "$PROJECT_PATH" ]; then
            cd "$PROJECTS_PATH"
            git clone https://github.com/guillermoVicenteGonzalez/vue-synth.git
          fi
          cd "$PROJECT_PATH"
          git pull

      - name: build docker container
        env:
          PROJECT_PATH: ${{secrets.PROJECT_PATH}}
        run: |
          cd "$PROJECT_PATH"
          docker compose up front-prod -d
